global using EntertainmentApp.Applicatoin;
global using MediatR;
global using EntertainmentApp.API.Attributes;
global using EntertainmentApp.API.Dtos;
global using EntertainmentApp.API.Helpers;
global using EntertainmentApp.Applicatoin.Common.Dtos;
global using EntertainmentApp.Applicatoin.Common.Models;
global using EntertainmentApp.Applicatoin.Features.Video;
global using EntertainmentApp.Applicatoin.Interfaces.Media;
global using EntertainmentApp.Shared.Exceptions;
global using Mapster;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using static EntertainmentApp.Applicatoin.Features.BookFeature.GetBookRefrenceDataHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.AudioStoryFeature.AddAudioStoryEpisodeHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.AudioStoryFeature.AddAudioStoryHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.AudioStoryFeature.DeleteAudioStoryEpisodeHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.AudioStoryFeature.DeleteAudioStoryHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.AudioStoryFeature.GetAudioStoryByIdHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.AudioStoryFeature.GetAudioStoryHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.AudioStoryFeature.UpdateAudioStoryHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.BookFeature.AddBookHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.BookFeature.DeleteBookHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.BookFeature.GetBookByIdHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.BookFeature.GetBookHandler;
global using  static EntertainmentApp.Applicatoin.Features.Story.BookFeature.UpdateBookHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.PodCastFeature.AddPodCastEpisodeHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.PodCastFeature.AddPodCastHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.PodCastFeature.DeletePodCastEpisodeHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.PodCastFeature.DeletePodCastHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.PodCastFeature.GetPodCastByIdHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.PodCastFeature.GetPodCastHandler;
global using static EntertainmentApp.Applicatoin.Features.Story.PodCastFeature.UpdatePodCastHandler;